const { spawnSync } = require('child_process');
const path = require('path');

const backendDir = path.resolve(__dirname, '..');

const queries = [
  // 1. Channel inserts
  `INSERT INTO streamerChannel (platform, channel_url, channel_name) SELECT 'YOUTUBE', 'https://www.youtube.com/@nagiri_ryune', '凪璃リュネ' WHERE NOT EXISTS (SELECT 1 FROM streamerChannel WHERE platform = 'YOUTUBE' AND channel_url = 'https://www.youtube.com/@nagiri_ryune');`,
  `INSERT INTO streamerChannel (platform, channel_url, channel_name) SELECT 'YOUTUBE', 'https://www.youtube.com/@kaguha_suzume', '赫羽すずめ' WHERE NOT EXISTS (SELECT 1 FROM streamerChannel WHERE platform = 'YOUTUBE' AND channel_url = 'https://www.youtube.com/@kaguha_suzume');`,
  `INSERT INTO streamerChannel (platform, channel_url, channel_name) SELECT 'YOUTUBE', 'https://www.youtube.com/@yomori_hana', '宵守はな' WHERE NOT EXISTS (SELECT 1 FROM streamerChannel WHERE platform = 'YOUTUBE' AND channel_url = 'https://www.youtube.com/@yomori_hana');`,
  `INSERT INTO streamerChannel (platform, channel_url, channel_name) SELECT 'YOUTUBE', 'https://www.youtube.com/@monbelma', '門ベルマ' WHERE NOT EXISTS (SELECT 1 FROM streamerChannel WHERE platform = 'YOUTUBE' AND channel_url = 'https://www.youtube.com/@monbelma');`,
  `INSERT INTO streamerChannel (platform, channel_url, channel_name) SELECT 'YOUTUBE', 'https://www.youtube.com/channel/UCrGyguoym8eIa-1RYDoBwhA', '尾咲いずな' WHERE NOT EXISTS (SELECT 1 FROM streamerChannel WHERE platform = 'YOUTUBE' AND channel_url = 'https://www.youtube.com/channel/UCrGyguoym8eIa-1RYDoBwhA');`,
  `INSERT INTO streamerChannel (platform, channel_url, channel_name) SELECT 'YOUTUBE', 'https://www.youtube.com/channel/UCPqpVes-qY123mJ-4HuMV0w', '可惜夜ろむ' WHERE NOT EXISTS (SELECT 1 FROM streamerChannel WHERE platform = 'YOUTUBE' AND channel_url = 'https://www.youtube.com/channel/UCPqpVes-qY123mJ-4HuMV0w');`,
  `INSERT INTO streamerChannel (platform, channel_url, channel_name) SELECT 'YOUTUBE', 'https://www.youtube.com/@SayoTsukina', '紗夜ツキナ' WHERE NOT EXISTS (SELECT 1 FROM streamerChannel WHERE platform = 'YOUTUBE' AND channel_url = 'https://www.youtube.com/@SayoTsukina');`,
  `INSERT INTO streamerChannel (platform, channel_url, channel_name) SELECT 'YOUTUBE', 'https://www.youtube.com/channel/UCd06jUO_R0Ow34ivhHFurtw', '夕涼伊月' WHERE NOT EXISTS (SELECT 1 FROM streamerChannel WHERE platform = 'YOUTUBE' AND channel_url = 'https://www.youtube.com/channel/UCd06jUO_R0Ow34ivhHFurtw');`,
  `INSERT INTO streamerChannel (platform, channel_url, channel_name) SELECT 'YOUTUBE', 'https://www.youtube.com/channel/UC4toMlO9gcVq13u2J7FwnUQ', 'ワドさん' WHERE NOT EXISTS (SELECT 1 FROM streamerChannel WHERE platform = 'YOUTUBE' AND channel_url = 'https://www.youtube.com/channel/UC4toMlO9gcVq13u2J7FwnUQ');`,
  `INSERT INTO streamerChannel (platform, channel_url, channel_name) SELECT 'YOUTUBE', 'https://www.youtube.com/channel/UC7KnnBYCYEkwt_iL0hRNZEg', '花埜いろha' WHERE NOT EXISTS (SELECT 1 FROM streamerChannel WHERE platform = 'YOUTUBE' AND channel_url = 'https://www.youtube.com/channel/UC7KnnBYCYEkwt_iL0hRNZEg');`,
  `UPDATE streamerChannel SET channel_name = '花埜いろは' WHERE platform = 'YOUTUBE' AND channel_url = 'https://www.youtube.com/channel/UC7KnnBYCYEkwt_iL0hRNZEg';`,
  `INSERT INTO streamerChannel (platform, channel_url, channel_name) SELECT 'YOUTUBE', 'https://www.youtube.com/channel/UCAYLF5eyxn0hxdRvkKdpWCA', '紫陽すの' WHERE NOT EXISTS (SELECT 1 FROM streamerChannel WHERE platform = 'YOUTUBE' AND channel_url = 'https://www.youtube.com/channel/UCAYLF5eyxn0hxdRvkKdpWCA');`,
  `INSERT INTO streamerChannel (platform, channel_url, channel_name) SELECT 'YOUTUBE', 'https://www.youtube.com/channel/UCuMX4dTLQ9QvIneOGQciGXQ', '乃愛ちゃん' WHERE NOT EXISTS (SELECT 1 FROM streamerChannel WHERE platform = 'YOUTUBE' AND channel_url = 'https://www.youtube.com/channel/UCuMX4dTLQ9QvIneOGQciGXQ');`,
  `INSERT INTO streamerChannel (platform, channel_url, channel_name) SELECT 'YOUTUBE', 'https://www.youtube.com/channel/UC2zS1jTYPnXzt0g3KMSDMFg', '愛妹ちこら' WHERE NOT EXISTS (SELECT 1 FROM streamerChannel WHERE platform = 'YOUTUBE' AND channel_url = 'https://www.youtube.com/channel/UC2zS1jTYPnXzt0g3KMSDMFg');`,
  `INSERT INTO streamerChannel (platform, channel_url, channel_name) SELECT 'YOUTUBE', 'https://www.youtube.com/channel/UCDjiYmrGfcZLBRhv4JdUDEw', '拝啓ノア' WHERE NOT EXISTS (SELECT 1 FROM streamerChannel WHERE platform = 'YOUTUBE' AND channel_url = 'https://www.youtube.com/channel/UCDjiYmrGfcZLBRhv4JdUDEw');`,
  `INSERT INTO streamerChannel (platform, channel_url, channel_name) SELECT 'YOUTUBE', 'https://www.youtube.com/channel/UCtwpDkzB6vP2iRvXizhYbOw', '結束かなで' WHERE NOT EXISTS (SELECT 1 FROM streamerChannel WHERE platform = 'YOUTUBE' AND channel_url = 'https://www.youtube.com/channel/UCtwpDkzB6vP2iRvXizhYbOw');`,
  `INSERT INTO streamerChannel (platform, channel_url, channel_name) SELECT 'YOUTUBE', 'https://www.youtube.com/channel/UCmDozJqKH7vYoiyHDY3MRJw', '柴田あん' WHERE NOT EXISTS (SELECT 1 FROM streamerChannel WHERE platform = 'YOUTUBE' AND channel_url = 'https://www.youtube.com/channel/UCmDozJqKH7vYoiyHDY3MRJw');`,
  `INSERT INTO streamerChannel (platform, channel_url, channel_name) SELECT 'YOUTUBE', 'https://www.youtube.com/channel/UCByrtcbQIyZuAFionmv0iTQ', 'タダまる。' WHERE NOT EXISTS (SELECT 1 FROM streamerChannel WHERE platform = 'YOUTUBE' AND channel_url = 'https://www.youtube.com/channel/UCByrtcbQIyZuAFionmv0iTQ');`,
  `INSERT INTO streamerChannel (platform, channel_url, channel_name) SELECT 'SOOP', 'https://www.sooplive.com/station/withsleep', '모냐?' WHERE NOT EXISTS (SELECT 1 FROM streamerChannel WHERE platform = 'SOOP' AND channel_url = 'https://www.sooplive.com/station/withsleep');`,
  `INSERT INTO streamerChannel (platform, channel_url, channel_name) SELECT 'CHZZK', 'https://chzzk.naver.com/c63f8c12f6d0178457b82413d45efd5a', '잘님' WHERE NOT EXISTS (SELECT 1 FROM streamerChannel WHERE platform = 'CHZZK' AND channel_url = 'https://chzzk.naver.com/c63f8c12f6d0178457b82413d45efd5a');`,
  `INSERT INTO streamerChannel (platform, channel_url, channel_name) SELECT 'YOUTUBE', 'https://www.youtube.com/channel/UCeDid7S1B971buJqXU9frGw', '散雲ヒユメ' WHERE NOT EXISTS (SELECT 1 FROM streamerChannel WHERE platform = 'YOUTUBE' AND channel_url = 'https://www.youtube.com/channel/UCeDid7S1B971buJqXU9frGw');`,
  `INSERT INTO streamerChannel (platform, channel_url, channel_name) SELECT 'YOUTUBE', 'https://www.youtube.com/channel/UCpQje3p1s3BiPEp3MVm76hQ', 'ガチ経営者VTuber組長' WHERE NOT EXISTS (SELECT 1 FROM streamerChannel WHERE platform = 'YOUTUBE' AND channel_url = 'https://www.youtube.com/channel/UCpQje3p1s3BiPEp3MVm76hQ');`,
  `INSERT INTO streamerChannel (platform, channel_url, channel_name) SELECT 'YOUTUBE', 'https://www.youtube.com/channel/UCpyHqDwJteNDblJ2tHtTXuA', '月深夜冥夜' WHERE NOT EXISTS (SELECT 1 FROM streamerChannel WHERE platform = 'YOUTUBE' AND channel_url = 'https://www.youtube.com/channel/UCpyHqDwJteNDblJ2tHtTXuA');`,

  // 2. Info inserts
  `INSERT INTO streamerChannel_info (channel_id, slug, display_name, profile_image_url, description, agency_name, debut_date, debut_time, timezone, start_at_utc, country_code) SELECT sc.id, 'nagiri-ryune', '凪璃リュネ', '', '凪璃リュ네의 버추얼 스트리머 첫 데뷔 방송입니다.', '개인세', '2026-08-26', '19:00', 'Asia/Seoul', '2026-08-26T10:00:00.000Z', 'JP' FROM streamerChannel sc WHERE sc.platform = 'YOUTUBE' AND sc.channel_url = 'https://www.youtube.com/@nagiri_ryune' AND NOT EXISTS (SELECT 1 FROM streamerChannel_info sci WHERE sci.channel_id = sc.id);`,
  `INSERT INTO streamerChannel_info (channel_id, slug, display_name, profile_image_url, description, agency_name, debut_date, debut_time, timezone, start_at_utc, country_code) SELECT sc.id, 'kaguha-suzume', '赫羽すずめ', '', '赫羽すずめ의 버추얼 스트리머 첫 데뷔 방송입니다.', '개인세', '2026-08-26', '19:30', 'Asia/Seoul', '2026-08-26T10:30:00.000Z', 'JP' FROM streamerChannel sc WHERE sc.platform = 'YOUTUBE' AND sc.channel_url = 'https://www.youtube.com/@kaguha_suzume' AND NOT EXISTS (SELECT 1 FROM streamerChannel_info sci WHERE sci.channel_id = sc.id);`,
  `INSERT INTO streamerChannel_info (channel_id, slug, display_name, profile_image_url, description, agency_name, debut_date, debut_time, timezone, start_at_utc, country_code) SELECT sc.id, 'yomori-hana', '宵守はな', '', '宵守はな의 버추얼 스트리머 첫 데뷔 방송입니다.', '개인세', '2026-08-26', '20:00', 'Asia/Seoul', '2026-08-26T11:00:00.000Z', 'JP' FROM streamerChannel sc WHERE sc.platform = 'YOUTUBE' AND sc.channel_url = 'https://www.youtube.com/@yomori_hana' AND NOT EXISTS (SELECT 1 FROM streamerChannel_info sci WHERE sci.channel_id = sc.id);`,
  `INSERT INTO streamerChannel_info (channel_id, slug, display_name, profile_image_url, description, agency_name, debut_date, debut_time, timezone, start_at_utc, country_code) SELECT sc.id, 'monbelma', '門ベルマ', '', '門ベルマ의 버추얼 스트리머 첫 데뷔 방송입니다.', '개인세', '2026-08-26', '20:30', 'Asia/Seoul', '2026-08-26T11:30:00.000Z', 'JP' FROM streamerChannel sc WHERE sc.platform = 'YOUTUBE' AND sc.channel_url = 'https://www.youtube.com/@monbelma' AND NOT EXISTS (SELECT 1 FROM streamerChannel_info sci WHERE sci.channel_id = sc.id);`,
  `INSERT INTO streamerChannel_info (channel_id, slug, display_name, profile_image_url, description, agency_name, debut_date, debut_time, timezone, start_at_utc, country_code) SELECT sc.id, 'osaki-izuna', '尾咲いずな', '', '尾咲いずな의 버추얼 스트리머 첫 데뷔 방송입니다.', '개인세', '2026-08-26', '22:00', 'Asia/Seoul', '2026-08-26T13:00:00.000Z', 'JP' FROM streamerChannel sc WHERE sc.platform = 'YOUTUBE' AND sc.channel_url = 'https://www.youtube.com/channel/UCrGyguoym8eIa-1RYDoBwhA' AND NOT EXISTS (SELECT 1 FROM streamerChannel_info sci WHERE sci.channel_id = sc.id);`,
  `INSERT INTO streamerChannel_info (channel_id, slug, display_name, profile_image_url, description, agency_name, debut_date, debut_time, timezone, start_at_utc, country_code) SELECT sc.id, 'atarayo-romu', '可惜夜ろむ', '', '可惜夜ろむ의 버추얼 스트리머 첫 데뷔 방송입니다.', '개인세', '2026-08-27', '19:00', 'Asia/Seoul', '2026-08-27T10:00:00.000Z', 'JP' FROM streamerChannel sc WHERE sc.platform = 'YOUTUBE' AND sc.channel_url = 'https://www.youtube.com/channel/UCPqpVes-qY123mJ-4HuMV0w' AND NOT EXISTS (SELECT 1 FROM streamerChannel_info sci WHERE sci.channel_id = sc.id);`,
  `INSERT INTO streamerChannel_info (channel_id, slug, display_name, profile_image_url, description, agency_name, debut_date, debut_time, timezone, start_at_utc, country_code) SELECT sc.id, 'sayo-tsukina', '紗夜ツキナ', '', '紗夜ツキナ의 버추얼 스트리머 첫 데뷔 방송입니다.', '개인세', '2026-08-27', '21:00', 'Asia/Seoul', '2026-08-27T12:00:00.000Z', 'JP' FROM streamerChannel sc WHERE sc.platform = 'YOUTUBE' AND sc.channel_url = 'https://www.youtube.com/@SayoTsukina' AND NOT EXISTS (SELECT 1 FROM streamerChannel_info sci WHERE sci.channel_id = sc.id);`,
  `INSERT INTO streamerChannel_info (channel_id, slug, display_name, profile_image_url, description, agency_name, debut_date, debut_time, timezone, start_at_utc, country_code) SELECT sc.id, 'yusuzumi-iduki', '夕涼伊月', '', '夕涼伊月의 버추얼 스트리머 첫 데뷔 방송입니다.', '개인세', '2026-08-28', '21:00', 'Asia/Seoul', '2026-08-28T12:00:00.000Z', 'JP' FROM streamerChannel sc WHERE sc.platform = 'YOUTUBE' AND sc.channel_url = 'https://www.youtube.com/channel/UCd06jUO_R0Ow34ivhHFurtw' AND NOT EXISTS (SELECT 1 FROM streamerChannel_info sci WHERE sci.channel_id = sc.id);`,
  `INSERT INTO streamerChannel_info (channel_id, slug, display_name, profile_image_url, description, agency_name, debut_date, debut_time, timezone, start_at_utc, country_code) SELECT sc.id, 'wadosan', 'ワドさん', '', 'ワドさん의 버추얼 스트리머 첫 데뷔 방송입니다.', '개인세', '2026-08-28', '21:00', 'Asia/Seoul', '2026-08-28T12:00:00.000Z', 'JP' FROM streamerChannel sc WHERE sc.platform = 'YOUTUBE' AND sc.channel_url = 'https://www.youtube.com/channel/UC4toMlO9gcVq13u2J7FwnUQ' AND NOT EXISTS (SELECT 1 FROM streamerChannel_info sci WHERE sci.channel_id = sc.id);`,
  `INSERT INTO streamerChannel_info (channel_id, slug, display_name, profile_image_url, description, agency_name, debut_date, debut_time, timezone, start_at_utc, country_code) SELECT sc.id, 'hanano-iroha', '花埜いろは', '', '花埜いろは의 버추얼 스트리머 첫 데뷔 방송입니다.', '개인세', '2026-08-28', '22:00', 'Asia/Seoul', '2026-08-28T13:00:00.000Z', 'JP' FROM streamerChannel sc WHERE sc.platform = 'YOUTUBE' AND sc.channel_url = 'https://www.youtube.com/channel/UC7KnnBYCYEkwt_iL0hRNZEg' AND NOT EXISTS (SELECT 1 FROM streamerChannel_info sci WHERE sci.channel_id = sc.id);`,
  `INSERT INTO streamerChannel_info (channel_id, slug, display_name, profile_image_url, description, agency_name, debut_date, debut_time, timezone, start_at_utc, country_code) SELECT sc.id, 'shiyo-suno', '紫陽すの', '', '紫陽すの의 버추얼 스트리머 첫 데뷔 방송입니다.', '개인세', '2026-08-29', '18:00', 'Asia/Seoul', '2026-08-29T09:00:00.000Z', 'JP' FROM streamerChannel sc WHERE sc.platform = 'YOUTUBE' AND sc.channel_url = 'https://www.youtube.com/channel/UCAYLF5eyxn0hxdRvkKdpWCA' AND NOT EXISTS (SELECT 1 FROM streamerChannel_info sci WHERE sci.channel_id = sc.id);`,
  `INSERT INTO streamerChannel_info (channel_id, slug, display_name, profile_image_url, description, agency_name, debut_date, debut_time, timezone, start_at_utc, country_code) SELECT sc.id, 'noachan', '乃愛ちゃん', '', '乃愛ちゃん의 버추얼 스트리머 첫 데뷔 방송입니다.', '개인세', '2026-08-29', '20:00', 'Asia/Seoul', '2026-08-29T11:00:00.000Z', 'JP' FROM streamerChannel sc WHERE sc.platform = 'YOUTUBE' AND sc.channel_url = 'https://www.youtube.com/channel/UCuMX4dTLQ9QvIneOGQciGXQ' AND NOT EXISTS (SELECT 1 FROM streamerChannel_info sci WHERE sci.channel_id = sc.id);`,
  `INSERT INTO streamerChannel_info (channel_id, slug, display_name, profile_image_url, description, agency_name, debut_date, debut_time, timezone, start_at_utc, country_code) SELECT sc.id, 'aimo-chikora', '愛妹ちこら', '', '愛妹ちこら의 버추얼 스트리머 첫 데뷔 방송입니다.', '개인세', '2026-08-29', '20:00', 'Asia/Seoul', '2026-08-29T11:00:00.000Z', 'JP' FROM streamerChannel sc WHERE sc.platform = 'YOUTUBE' AND sc.channel_url = 'https://www.youtube.com/channel/UC2zS1jTYPnXzt0g3KMSDMFg' AND NOT EXISTS (SELECT 1 FROM streamerChannel_info sci WHERE sci.channel_id = sc.id);`,
  `INSERT INTO streamerChannel_info (channel_id, slug, display_name, profile_image_url, description, agency_name, debut_date, debut_time, timezone, start_at_utc, country_code) SELECT sc.id, 'haikei-noa', '拝啓ノア', '', '拝啓ノア의 버추얼 스트리머 첫 데뷔 방송입니다.', '개인세', '2026-08-29', '20:00', 'Asia/Seoul', '2026-08-29T11:00:00.000Z', 'JP' FROM streamerChannel sc WHERE sc.platform = 'YOUTUBE' AND sc.channel_url = 'https://www.youtube.com/channel/UCDjiYmrGfcZLBRhv4JdUDEw' AND NOT EXISTS (SELECT 1 FROM streamerChannel_info sci WHERE sci.channel_id = sc.id);`,
  `INSERT INTO streamerChannel_info (channel_id, slug, display_name, profile_image_url, description, agency_name, debut_date, debut_time, timezone, start_at_utc, country_code) SELECT sc.id, 'kessoku-kanade', '結束かなで', '', '結束かなで의 버추얼 스트리머 첫 데뷔 방송입니다.', '개인세', '2026-08-29', '21:00', 'Asia/Seoul', '2026-08-29T12:00:00.000Z', 'JP' FROM streamerChannel sc WHERE sc.platform = 'YOUTUBE' AND sc.channel_url = 'https://www.youtube.com/channel/UCtwpDkzB6vP2iRvXizhYbOw' AND NOT EXISTS (SELECT 1 FROM streamerChannel_info sci WHERE sci.channel_id = sc.id);`,
  `INSERT INTO streamerChannel_info (channel_id, slug, display_name, profile_image_url, description, agency_name, debut_date, debut_time, timezone, start_at_utc, country_code) SELECT sc.id, 'shibata-an', '柴田あん', '', '柴田あん의 버추얼 스트리머 첫 데뷔 방송입니다.', '개인세', '2026-08-29', '22:00', 'Asia/Seoul', '2026-08-29T13:00:00.000Z', 'JP' FROM streamerChannel sc WHERE sc.platform = 'YOUTUBE' AND sc.channel_url = 'https://www.youtube.com/channel/UCmDozJqKH7vYoiyHDY3MRJw' AND NOT EXISTS (SELECT 1 FROM streamerChannel_info sci WHERE sci.channel_id = sc.id);`,
  `INSERT INTO streamerChannel_info (channel_id, slug, display_name, profile_image_url, description, agency_name, debut_date, debut_time, timezone, start_at_utc, country_code) SELECT sc.id, 'tadamaru', 'タダまる。', '', 'タダまる。의 버추얼 스트리머 첫 데뷔 방송입니다.', '개인세', '2026-08-29', '22:15', 'Asia/Seoul', '2026-08-29T13:15:00.000Z', 'JP' FROM streamerChannel sc WHERE sc.platform = 'YOUTUBE' AND sc.channel_url = 'https://www.youtube.com/channel/UCByrtcbQIyZuAFionmv0iTQ' AND NOT EXISTS (SELECT 1 FROM streamerChannel_info sci WHERE sci.channel_id = sc.id);`,
  `INSERT INTO streamerChannel_info (channel_id, slug, display_name, profile_image_url, description, agency_name, debut_date, debut_time, timezone, start_at_utc, country_code) SELECT sc.id, 'withsleep', '모냐?', 'https://profile.img.sooplive.co.kr/LOGO/wi/withsleep/withsleep.jpg', '모냐? 버추얼 스트리머의 첫 데뷔 방송입니다.', '개인세', '2026-08-30', '10:00', 'Asia/Seoul', '2026-08-30T01:00:00.000Z', 'KR' FROM streamerChannel sc WHERE sc.platform = 'SOOP' AND sc.channel_url = 'https://www.sooplive.com/station/withsleep' AND NOT EXISTS (SELECT 1 FROM streamerChannel_info sci WHERE sci.channel_id = sc.id);`,
  `INSERT INTO streamerChannel_info (channel_id, slug, display_name, profile_image_url, description, agency_name, debut_date, debut_time, timezone, start_at_utc, country_code) SELECT sc.id, 'zalnim', '잘님', 'https://nng-phinf.pstatic.net/MjAyNjA3MzFfMTA1/MDAxNzg1NDk5MTc5ODg1.h9U0UH61oS6e10DviuzVGhw5YChkdkr1SRlF6JEvD60g.HzySnv3x8vCGwgo81ufux9oUBqj-rPno0CpuhpZWockg.PNG/image.png', '네 마음을 이해하고 싶은 창조의 여신. 토크, 타로, 그림, 게임! *데뷔방송- 2026년 8월30일 낮3시 문의: tokuhane@gmail.com', '개인세', '2026-08-30', '15:00', 'Asia/Seoul', '2026-08-30T06:00:00.000Z', 'KR' FROM streamerChannel sc WHERE sc.platform = 'CHZZK' AND sc.channel_url = 'https://chzzk.naver.com/c63f8c12f6d0178457b82413d45efd5a' AND NOT EXISTS (SELECT 1 FROM streamerChannel_info sci WHERE sci.channel_id = sc.id);`,
  `INSERT INTO streamerChannel_info (channel_id, slug, display_name, profile_image_url, description, agency_name, debut_date, debut_time, timezone, start_at_utc, country_code) SELECT sc.id, 'chirigumo-hiyume', '散雲ヒユメ', '', '散雲ヒユメ의 버추얼 스트리머 첫 데뷔 방송입니다.', '개인세', '2026-08-30', '21:00', 'Asia/Seoul', '2026-08-30T12:00:00.000Z', 'JP' FROM streamerChannel sc WHERE sc.platform = 'YOUTUBE' AND sc.channel_url = 'https://www.youtube.com/channel/UCeDid7S1B971buJqXU9frGw' AND NOT EXISTS (SELECT 1 FROM streamerChannel_info sci WHERE sci.channel_id = sc.id);`,
  `INSERT INTO streamerChannel_info (channel_id, slug, display_name, profile_image_url, description, agency_name, debut_date, debut_time, timezone, start_at_utc, country_code) SELECT sc.id, 'kumicho', 'ガチ経営者VTuber組長', '', 'ガチ経営者VTuber組長의 버추얼 스트리머 첫 데뷔 방송입니다.', '개인세', '2026-08-31', '20:00', 'Asia/Seoul', '2026-08-31T11:00:00.000Z', 'JP' FROM streamerChannel sc WHERE sc.platform = 'YOUTUBE' AND sc.channel_url = 'https://www.youtube.com/channel/UCpQje3p1s3BiPEp3MVm76hQ' AND NOT EXISTS (SELECT 1 FROM streamerChannel_info sci WHERE sci.channel_id = sc.id);`,
  `INSERT INTO streamerChannel_info (channel_id, slug, display_name, profile_image_url, description, agency_name, debut_date, debut_time, timezone, start_at_utc, country_code) SELECT sc.id, 'tsukimi-meiya', '月深夜冥夜', '', '月深夜冥夜의 버추얼 스트리머 첫 데뷔 방송입니다.', '개인세', '2026-08-31', '23:00', 'Asia/Seoul', '2026-08-31T14:00:00.000Z', 'JP' FROM streamerChannel sc WHERE sc.platform = 'YOUTUBE' AND sc.channel_url = 'https://www.youtube.com/channel/UCpyHqDwJteNDblJ2tHtTXuA' AND NOT EXISTS (SELECT 1 FROM streamerChannel_info sci WHERE sci.channel_id = sc.id);`,

  // 3. 토모♪ UPDATE
  `UPDATE streamerChannel_info SET debut_date = '2026-08-26', debut_time = '13:00', start_at_utc = '2026-08-26T04:00:00.000Z' WHERE channel_id IN (SELECT id FROM streamerChannel WHERE platform = 'SOOP' AND channel_url = 'https://www.sooplive.com/station/warabimochi0');`
];

console.log(`🚀 Executing ${queries.length} queries on remote D1 database (vdebut-db)...`);

for (let i = 0; i < queries.length; i++) {
  const q = queries[i];
  console.log(`\n[${i + 1}/${queries.length}] Executing: ${q.substring(0, 80)}...`);

  const res = spawnSync('cmd.exe', ['/c', 'npx', 'wrangler', 'd1', 'execute', 'vdebut-db', '--remote', `--command=${q}`, '--json'], {
    cwd: backendDir,
    encoding: 'utf-8'
  });

  if (res.status !== 0) {
    console.error(`❌ Query ${i + 1} failed with status ${res.status}`);
    console.error('stderr:', res.stderr);
    console.error('stdout:', res.stdout);
    process.exit(1);
  }

  try {
    const parsed = JSON.parse(res.stdout);
    console.log(`✅ Success: ${JSON.stringify(parsed[0]?.meta?.changes ?? 0)} changes, duration: ${parsed[0]?.meta?.duration ?? 0}ms`);
  } catch {
    console.log('✅ Success (non-json output received)');
  }
}

console.log('\n🎉 All Migration 0021 queries executed successfully on remote D1 database!');
