const { spawnSync } = require('child_process');
const path = require('path');

const backendDir = path.resolve(__dirname, '..');

const queries = [
  // 1. Channel inserts
  `INSERT INTO streamerChannel (platform, channel_url, channel_name) SELECT 'SOOP', 'https://www.sooplive.com/station/beastrin', '맹수린' WHERE NOT EXISTS (SELECT 1 FROM streamerChannel WHERE platform = 'SOOP' AND channel_url = 'https://www.sooplive.com/station/beastrin');`,
  `INSERT INTO streamerChannel (platform, channel_url, channel_name) SELECT 'SOOP', 'https://www.sooplive.com/station/cy930221', '율개_' WHERE NOT EXISTS (SELECT 1 FROM streamerChannel WHERE platform = 'SOOP' AND channel_url = 'https://www.sooplive.com/station/cy930221');`,
  `INSERT INTO streamerChannel (platform, channel_url, channel_name) SELECT 'SOOP', 'https://www.sooplive.com/station/warabimochi0', '토모♪' WHERE NOT EXISTS (SELECT 1 FROM streamerChannel WHERE platform = 'SOOP' AND channel_url = 'https://www.sooplive.com/station/warabimochi0');`,
  `INSERT INTO streamerChannel (platform, channel_url, channel_name) SELECT 'YOUTUBE', 'https://www.youtube.com/@yuyunga', '癒月沙羅🍀ゆゆんが' WHERE NOT EXISTS (SELECT 1 FROM streamerChannel WHERE platform = 'YOUTUBE' AND channel_url = 'https://www.youtube.com/@yuyunga');`,
  `INSERT INTO streamerChannel (platform, channel_url, channel_name) SELECT 'YOUTUBE', 'https://www.youtube.com/channel/UCT0D59ZmybXfae08GiMHSlQ', 'ねむくま まふゆ / Mafuyu Nemukuma' WHERE NOT EXISTS (SELECT 1 FROM streamerChannel WHERE platform = 'YOUTUBE' AND channel_url = 'https://www.youtube.com/channel/UCT0D59ZmybXfae08GiMHSlQ');`,
  `INSERT INTO streamerChannel (platform, channel_url, channel_name) SELECT 'YOUTUBE', 'https://www.youtube.com/channel/UCx6rTx9V_chxAkn4luzyRpQ', '請叫我披薩 Pinasalia' WHERE NOT EXISTS (SELECT 1 FROM streamerChannel WHERE platform = 'YOUTUBE' AND channel_url = 'https://www.youtube.com/channel/UCx6rTx9V_chxAkn4luzyRpQ');`,
  `INSERT INTO streamerChannel (platform, channel_url, channel_name) SELECT 'CHZZK', 'https://chzzk.naver.com/3a5cc666e57aee0eb797a10d6e710fb2', '다번님' WHERE NOT EXISTS (SELECT 1 FROM streamerChannel WHERE platform = 'CHZZK' AND channel_url = 'https://chzzk.naver.com/3a5cc666e57aee0eb797a10d6e710fb2');`,
  `INSERT INTO streamerChannel (platform, channel_url, channel_name) SELECT 'CHZZK', 'https://chzzk.naver.com/90d8df90bfb9b2a2a1aaf6a3f09d1221', '0ml 제로미리' WHERE NOT EXISTS (SELECT 1 FROM streamerChannel WHERE platform = 'CHZZK' AND channel_url = 'https://chzzk.naver.com/90d8df90bfb9b2a2a1aaf6a3f09d1221');`,
  `INSERT INTO streamerChannel (platform, channel_url, channel_name) SELECT 'SOOP', 'https://www.sooplive.com/station/jjrroesem', '슷쟝、' WHERE NOT EXISTS (SELECT 1 FROM streamerChannel WHERE platform = 'SOOP' AND channel_url = 'https://www.sooplive.com/station/jjrroesem');`,
  `INSERT INTO streamerChannel (platform, channel_url, channel_name) SELECT 'CHZZK', 'https://chzzk.naver.com/dae941286535b489b5282a8910fb0363', '시노미야 카나' WHERE NOT EXISTS (SELECT 1 FROM streamerChannel WHERE platform = 'CHZZK' AND channel_url = 'https://chzzk.naver.com/dae941286535b489b5282a8910fb0363');`,
  `INSERT INTO streamerChannel (platform, channel_url, channel_name) SELECT 'CHZZK', 'https://chzzk.naver.com/82e55f09f2235ac3d23c155bf20877de', '김레율 LEYUL' WHERE NOT EXISTS (SELECT 1 FROM streamerChannel WHERE platform = 'CHZZK' AND channel_url = 'https://chzzk.naver.com/82e55f09f2235ac3d23c155bf20877de');`,
  `INSERT INTO streamerChannel (platform, channel_url, channel_name) SELECT 'CHZZK', 'https://chzzk.naver.com/dac7140d8871c1eb40dfc9dbdbdc4671', '히모리 키코' WHERE NOT EXISTS (SELECT 1 FROM streamerChannel WHERE platform = 'CHZZK' AND channel_url = 'https://chzzk.naver.com/dac7140d8871c1eb40dfc9dbdbdc4671');`,
  `INSERT INTO streamerChannel (platform, channel_url, channel_name) SELECT 'CHZZK', 'https://chzzk.naver.com/8292f415bf4949a508539b1332e059dd', '홍림' WHERE NOT EXISTS (SELECT 1 FROM streamerChannel WHERE platform = 'CHZZK' AND channel_url = 'https://chzzk.naver.com/8292f415bf4949a508539b1332e059dd');`,
  `INSERT INTO streamerChannel (platform, channel_url, channel_name) SELECT 'SOOP', 'https://www.sooplive.com/station/waekqm', '쿄카_' WHERE NOT EXISTS (SELECT 1 FROM streamerChannel WHERE platform = 'SOOP' AND channel_url = 'https://www.sooplive.com/station/waekqm');`,
  `INSERT INTO streamerChannel (platform, channel_url, channel_name) SELECT 'CHZZK', 'https://chzzk.naver.com/3b83140bc120a677646263b51d026fb8', '햅하리 Hepharii' WHERE NOT EXISTS (SELECT 1 FROM streamerChannel WHERE platform = 'CHZZK' AND channel_url = 'https://chzzk.naver.com/3b83140bc120a677646263b51d026fb8');`,
  `INSERT INTO streamerChannel (platform, channel_url, channel_name) SELECT 'CHZZK', 'https://chzzk.naver.com/8586c48ff92c6a2c7ba24937d4c360eb', '채루나 LUNA' WHERE NOT EXISTS (SELECT 1 FROM streamerChannel WHERE platform = 'CHZZK' AND channel_url = 'https://chzzk.naver.com/8586c48ff92c6a2c7ba24937d4c360eb');`,
  `INSERT INTO streamerChannel (platform, channel_url, channel_name) SELECT 'YOUTUBE', 'https://www.youtube.com/@yoru0310', 'yoru△03:10' WHERE NOT EXISTS (SELECT 1 FROM streamerChannel WHERE platform = 'YOUTUBE' AND channel_url = 'https://www.youtube.com/@yoru0310');`,
  `INSERT INTO streamerChannel (platform, channel_url, channel_name) SELECT 'SOOP', 'https://www.sooplive.com/station/default02', '연빛yeonvvit' WHERE NOT EXISTS (SELECT 1 FROM streamerChannel WHERE platform = 'SOOP' AND channel_url = 'https://www.sooplive.com/station/default02');`,

  // 2. Info inserts (if not exists)
  `INSERT INTO streamerChannel_info (channel_id, slug, display_name, profile_image_url, description, agency_name, debut_date, debut_time, timezone, start_at_utc, country_code) SELECT sc.id, 'beastrin', '맹수린', 'https://profile.img.sooplive.co.kr/LOGO/be/beastrin/beastrin.jpg', '맹수린 버추얼 스트리머의 첫 데뷔 방송입니다.', '개인세', '2026-08-23', '14:00', 'Asia/Seoul', '2026-08-23T05:00:00.000Z', 'KR' FROM streamerChannel sc WHERE sc.platform = 'SOOP' AND sc.channel_url = 'https://www.sooplive.com/station/beastrin' AND NOT EXISTS (SELECT 1 FROM streamerChannel_info sci WHERE sci.channel_id = sc.id);`,
  `INSERT INTO streamerChannel_info (channel_id, slug, display_name, profile_image_url, description, agency_name, debut_date, debut_time, timezone, start_at_utc, country_code) SELECT sc.id, 'yulgae', '율개_', 'https://profile.img.sooplive.co.kr/LOGO/cy/cy930221/cy930221.jpg', '율개_ 버추얼 스트리머의 첫 데뷔 방송입니다.', '개인세', '2026-08-24', '20:00', 'Asia/Seoul', '2026-08-24T11:00:00.000Z', 'KR' FROM streamerChannel sc WHERE sc.platform = 'SOOP' AND sc.channel_url = 'https://www.sooplive.com/station/cy930221' AND NOT EXISTS (SELECT 1 FROM streamerChannel_info sci WHERE sci.channel_id = sc.id);`,
  `INSERT INTO streamerChannel_info (channel_id, slug, display_name, profile_image_url, description, agency_name, debut_date, debut_time, timezone, start_at_utc, country_code) SELECT sc.id, 'tomo', '토모♪', 'https://profile.img.sooplive.co.kr/LOGO/wa/warabimochi0/warabimochi0.jpg', '토모♪ 버추얼 스트리머의 첫 데뷔 방송입니다.', '개인세', '2026-08-25', '13:00', 'Asia/Seoul', '2026-08-25T04:00:00.000Z', 'KR' FROM streamerChannel sc WHERE sc.platform = 'SOOP' AND sc.channel_url = 'https://www.sooplive.com/station/warabimochi0' AND NOT EXISTS (SELECT 1 FROM streamerChannel_info sci WHERE sci.channel_id = sc.id);`,
  `INSERT INTO streamerChannel_info (channel_id, slug, display_name, profile_image_url, description, agency_name, debut_date, debut_time, timezone, start_at_utc, country_code) SELECT sc.id, 'yuzuki-sara', '癒月沙羅🍀ゆゆんが', 'https://yt3.googleusercontent.com/1DvFwUHExxqmtroIWBDegjKg7BS9Mry_XDLbWqJitmCKSjy4ZTg2ibaYhvGOoieRf-n7LGEP2A=s900-c-k-c0x00ffffff-no-rj', 'イラスト動画を制作している癒月沙羅です。モモンガの女の子「ゆゆんが」と一緒に、日常や一次創作を発信しています。', '개인세', '2026-08-25', '20:25', 'Asia/Seoul', '2026-08-25T11:25:00.000Z', 'JP' FROM streamerChannel sc WHERE sc.platform = 'YOUTUBE' AND sc.channel_url = 'https://www.youtube.com/@yuyunga' AND NOT EXISTS (SELECT 1 FROM streamerChannel_info sci WHERE sci.channel_id = sc.id);`,
  `INSERT INTO streamerChannel_info (channel_id, slug, display_name, profile_image_url, description, agency_name, debut_date, debut_time, timezone, start_at_utc, country_code) SELECT sc.id, 'nemukuma-mafuyu', 'ねむくま まふゆ / Mafuyu Nemukuma', 'https://yt3.googleusercontent.com/8rEJVyB0qOUdeBJIQ1cpwgHWr5MK79CZN_OpwWjLf-W7aa952QNE2TdN5Evx4ER7VaVPr9lo=s900-c-k-c0x00ffffff-no-rj', '個人勢┊︎ くまとねこのハーフポンコツ天使Vsinger໒꒱· ﾟ 8월 25일 데뷔✨ mama : 摘星飞鱼 様', '개인세', '2026-08-25', '21:00', 'Asia/Seoul', '2026-08-25T12:00:00.000Z', 'JP' FROM streamerChannel sc WHERE sc.platform = 'YOUTUBE' AND sc.channel_url = 'https://www.youtube.com/channel/UCT0D59ZmybXfae08GiMHSlQ' AND NOT EXISTS (SELECT 1 FROM streamerChannel_info sci WHERE sci.channel_id = sc.id);`,
  `INSERT INTO streamerChannel_info (channel_id, slug, display_name, profile_image_url, description, agency_name, debut_date, debut_time, timezone, start_at_utc, country_code) SELECT sc.id, 'pinasalia', '請叫我披薩 Pinasalia', 'https://yt3.googleusercontent.com/g1I-yjW-28oEfg171nul0cCm5_9p0XjGNbZXM5ymlIIUojs6_3IKFGdo5EaE8M5DWNRwR5-DPQ0=s900-c-k-c0x00ffffff-no-rj', '你好！請叫我披薩，希望你今天過的好！', '개인세', '2026-08-25', '21:00', 'Asia/Seoul', '2026-08-25T12:00:00.000Z', 'US' FROM streamerChannel sc WHERE sc.platform = 'YOUTUBE' AND sc.channel_url = 'https://www.youtube.com/channel/UCx6rTx9V_chxAkn4luzyRpQ' AND NOT EXISTS (SELECT 1 FROM streamerChannel_info sci WHERE sci.channel_id = sc.id);`,
  `INSERT INTO streamerChannel_info (channel_id, slug, display_name, profile_image_url, description, agency_name, debut_date, debut_time, timezone, start_at_utc, country_code) SELECT sc.id, 'dabeon', '다번님', 'https://nng-phinf.pstatic.net/MjAyNjA4MTZfMTM3/MDAxNzg2ODYyOTk2NTI2.qNOvNrmMICOLSE_CR8ONO0zpcyIAybvux8RmlK04WAAg.Bdt9zOZQkxqL_PlUdCefUyEWzMYZuKqEXDhEFFRtxz8g.PNG/image.png', '다번님 버추얼 스트리머의 첫 데뷔 방송입니다.', '개인세', '2026-08-26', '14:00', 'Asia/Seoul', '2026-08-26T05:00:00.000Z', 'KR' FROM streamerChannel sc WHERE sc.platform = 'CHZZK' AND sc.channel_url = 'https://chzzk.naver.com/3a5cc666e57aee0eb797a10d6e710fb2' AND NOT EXISTS (SELECT 1 FROM streamerChannel_info sci WHERE sci.channel_id = sc.id);`,
  `INSERT INTO streamerChannel_info (channel_id, slug, display_name, profile_image_url, description, agency_name, debut_date, debut_time, timezone, start_at_utc, country_code) SELECT sc.id, '0ml-zeromili', '0ml 제로미리', 'https://nng-phinf.pstatic.net/MjAyNjA2MTRfMTI4/MDAxNzgxNDM4NzY0NDEw.1oQwHG18HvYb2YJkhvg9RbBKiVXdAN36-Lk0r-6nVkwg.csLLADplFXzAYGH7oabedr7aXelpWiAdW6f8JAIi9eUg.JPEG/image.jpg', '8월 28일 오후(낮) 12시 데뷔 예정 메일: g3s4nn@gmail.com', '개인세', '2026-08-28', '12:00', 'Asia/Seoul', '2026-08-28T03:00:00.000Z', 'KR' FROM streamerChannel sc WHERE sc.platform = 'CHZZK' AND sc.channel_url = 'https://chzzk.naver.com/90d8df90bfb9b2a2a1aaf6a3f09d1221' AND NOT EXISTS (SELECT 1 FROM streamerChannel_info sci WHERE sci.channel_id = sc.id);`,
  `INSERT INTO streamerChannel_info (channel_id, slug, display_name, profile_image_url, description, agency_name, debut_date, debut_time, timezone, start_at_utc, country_code) SELECT sc.id, 'seutjyang', '슷쟝、', 'https://profile.img.sooplive.co.kr/LOGO/jj/jjrroesem/jjrroesem.jpg', '슷쟝、 버추얼 스트리머의 첫 데뷔 방송입니다.', '개인세', '2026-08-28', '14:00', 'Asia/Seoul', '2026-08-28T05:00:00.000Z', 'KR' FROM streamerChannel sc WHERE sc.platform = 'SOOP' AND sc.channel_url = 'https://www.sooplive.com/station/jjrroesem' AND NOT EXISTS (SELECT 1 FROM streamerChannel_info sci WHERE sci.channel_id = sc.id);`,
  `INSERT INTO streamerChannel_info (channel_id, slug, display_name, profile_image_url, description, agency_name, debut_date, debut_time, timezone, start_at_utc, country_code) SELECT sc.id, 'shinomiya-kana', '시노미야 카나', 'https://nng-phinf.pstatic.net/MjAyNTEyMjBfMTU3/MDAxNzY2MjIzMzA3OTQ1.fGLFXPbDy222nLnwo_zpxpFFvQEWng0gpnUouzzaEd8g.ZKXkkW2fpM3Dst0msddZR6c1um53GaT89WOb0mjORXIg.JPEG/image.jpg', '❗2026년 8월 28일 오후 6시 데뷔❗', '개인세', '2026-08-28', '18:00', 'Asia/Seoul', '2026-08-28T09:00:00.000Z', 'KR' FROM streamerChannel sc WHERE sc.platform = 'CHZZK' AND sc.channel_url = 'https://chzzk.naver.com/dae941286535b489b5282a8910fb0363' AND NOT EXISTS (SELECT 1 FROM streamerChannel_info sci WHERE sci.channel_id = sc.id);`,
  `INSERT INTO streamerChannel_info (channel_id, slug, display_name, profile_image_url, description, agency_name, debut_date, debut_time, timezone, start_at_utc, country_code) SELECT sc.id, 'kim-leyul', '김레율 LEYUL', 'https://nng-phinf.pstatic.net/MjAyNTAzMjNfMTM2/MDAxNzQyNzEwMDY4NzEx.S2Hn6yRoBeel1j-_-6MgTRUFgU3ZjT854l96H3PLybIg.ptbUifqkw2JYaZwwg2uMdEIv7BlCNSdBeq9F_DbJ0w4g.PNG/C15DF10A-457D-46EE-A6AE-94389F9D762E-1742710068.png', '[STAR:VERSE] 스타버스 1기생 김레율입니다! ෆ(˶''ᵕ''˶マ⟆ෆ', 'STAR:VERSE', '2026-08-28', '20:00', 'Asia/Seoul', '2026-08-28T11:00:00.000Z', 'KR' FROM streamerChannel sc WHERE sc.platform = 'CHZZK' AND sc.channel_url = 'https://chzzk.naver.com/82e55f09f2235ac3d23c155bf20877de' AND NOT EXISTS (SELECT 1 FROM streamerChannel_info sci WHERE sci.channel_id = sc.id);`,
  `INSERT INTO streamerChannel_info (channel_id, slug, display_name, profile_image_url, description, agency_name, debut_date, debut_time, timezone, start_at_utc, country_code) SELECT sc.id, 'himori-kiko', '히모리 키코', 'https://nng-phinf.pstatic.net/MjAyNjA4MThfNTYg/MDAxNzg2OTk1MjE0NzUw.hhUNRTUdiPXJZW-3TfubZh92HBzwhe3wezs9WxuekIkg.t_PN_pYqIMKNtqyMjdYNnTr93dgjyi3bawGYJ3cOc9cg.JPEG/image.jpg', '방구석 묘큐버스 키코, 드디어 세상과 연결되다! 8월 28일 PM 8시 데뷔! 💻✨ himorikiko@naver.com', '개인세', '2026-08-28', '20:00', 'Asia/Seoul', '2026-08-28T11:00:00.000Z', 'KR' FROM streamerChannel sc WHERE sc.platform = 'CHZZK' AND sc.channel_url = 'https://chzzk.naver.com/dac7140d8871c1eb40dfc9dbdbdc4671' AND NOT EXISTS (SELECT 1 FROM streamerChannel_info sci WHERE sci.channel_id = sc.id);`,
  `INSERT INTO streamerChannel_info (channel_id, slug, display_name, profile_image_url, description, agency_name, debut_date, debut_time, timezone, start_at_utc, country_code) SELECT sc.id, 'hongrim', '홍림', 'https://nng-phinf.pstatic.net/MjAyNjA4MTFfMjYy/MDAxNzg2NDU2MjAxNTgz.gl_y0Nd960O3Utle81yyo4BUwDBUDnv59NkyG1irausg.TFJ5cRWHS2c63COrvCSKugJEgl8VKipE2MpWz_J9alUg.PNG/image.png', '🕯️사주 버튜버 홍림🌙 8. 28.(금) PM 08:00 첫 방송', '개인세', '2026-08-28', '20:00', 'Asia/Seoul', '2026-08-28T11:00:00.000Z', 'KR' FROM streamerChannel sc WHERE sc.platform = 'CHZZK' AND sc.channel_url = 'https://chzzk.naver.com/8292f415bf4949a508539b1332e059dd' AND NOT EXISTS (SELECT 1 FROM streamerChannel_info sci WHERE sci.channel_id = sc.id);`,
  `INSERT INTO streamerChannel_info (channel_id, slug, display_name, profile_image_url, description, agency_name, debut_date, debut_time, timezone, start_at_utc, country_code) SELECT sc.id, 'kyoka', '쿄카_', 'https://profile.img.sooplive.co.kr/LOGO/wa/waekqm/waekqm.jpg', '쿄카_ 버추얼 스트리머의 첫 데뷔 방송입니다.', '개인세', '2026-08-29', '12:00', 'Asia/Seoul', '2026-08-29T03:00:00.000Z', 'KR' FROM streamerChannel sc WHERE sc.platform = 'SOOP' AND sc.channel_url = 'https://www.sooplive.com/station/waekqm' AND NOT EXISTS (SELECT 1 FROM streamerChannel_info sci WHERE sci.channel_id = sc.id);`,
  `INSERT INTO streamerChannel_info (channel_id, slug, display_name, profile_image_url, description, agency_name, debut_date, debut_time, timezone, start_at_utc, country_code) SELECT sc.id, 'hepharii', '햅하리 Hepharii', 'https://nng-phinf.pstatic.net/MjAyNjA3MDVfMTIz/MDAxNzgzMjQxNjE3ODI2.suWJBK9Rd6-xlU3fAIg3BXye6W0Pus5plZBFeconTEAg.7VM8oZjeTzcpM7ks3c3C-XnDvNIA5wignN4M8k65OVIg.PNG/image.png', '봉봉..🫧', '개인세', '2026-08-29', '12:00', 'Asia/Seoul', '2026-08-29T03:00:00.000Z', 'KR' FROM streamerChannel sc WHERE sc.platform = 'CHZZK' AND sc.channel_url = 'https://chzzk.naver.com/3b83140bc120a677646263b51d026fb8' AND NOT EXISTS (SELECT 1 FROM streamerChannel_info sci WHERE sci.channel_id = sc.id);`,
  `INSERT INTO streamerChannel_info (channel_id, slug, display_name, profile_image_url, description, agency_name, debut_date, debut_time, timezone, start_at_utc, country_code) SELECT sc.id, 'chae-luna', '채루나 LUNA', 'https://nng-phinf.pstatic.net/MjAyNjA4MjBfMjMz/MDAxNzg3MjIyNTA1ODcx.WZDTT-m7RC-Ro8wUY-qUz2bWQWgBI_kez_jgul31ahog.5iSh9stq6c9XeiNlfNKXafEOAKrzDSReBUlRREKUOgQg.PNG/image.png', '2026.08.29 03:00PM [STAR:VERSE] 스타버스 1기생 채루나입니다아아!!!!', 'STAR:VERSE', '2026-08-29', '15:00', 'Asia/Seoul', '2026-08-29T06:00:00.000Z', 'KR' FROM streamerChannel sc WHERE sc.platform = 'CHZZK' AND sc.channel_url = 'https://chzzk.naver.com/8586c48ff92c6a2c7ba24937d4c360eb' AND NOT EXISTS (SELECT 1 FROM streamerChannel_info sci WHERE sci.channel_id = sc.id);`,
  `INSERT INTO streamerChannel_info (channel_id, slug, display_name, profile_image_url, description, agency_name, debut_date, debut_time, timezone, start_at_utc, country_code) SELECT sc.id, 'yoru0310', 'yoru△03:10', 'https://yt3.googleusercontent.com/SmC1yuSiHc7zRqlo0H2CMVWZj4NfoNhJd5fwdtKYZM9RXLITFKrdgLxaTinajfz5gWQ3npbZ=s900-c-k-c0x00ffffff-no-rj', '【yoru△03:10】(よるくん) ハスキーボイス의 크리에이터 Vtuber. きみとまったりチルタイム。お休み前にどうぞ。', '개인세', '2026-08-29', '22:00', 'Asia/Seoul', '2026-08-29T13:00:00.000Z', 'JP' FROM streamerChannel sc WHERE sc.platform = 'YOUTUBE' AND sc.channel_url = 'https://www.youtube.com/@yoru0310' AND NOT EXISTS (SELECT 1 FROM streamerChannel_info sci WHERE sci.channel_id = sc.id);`,
  `INSERT INTO streamerChannel_info (channel_id, slug, display_name, profile_image_url, description, agency_name, debut_date, debut_time, timezone, start_at_utc, country_code) SELECT sc.id, 'yeonvvit', '연빛yeonvvit', 'https://profile.img.sooplive.co.kr/LOGO/de/default02/default02.jpg', '연빛yeonvvit 버추얼 스트리머의 첫 데뷔 방송입니다.', '개인세', '2026-08-30', '14:00', 'Asia/Seoul', '2026-08-30T05:00:00.000Z', 'KR' FROM streamerChannel sc WHERE sc.platform = 'SOOP' AND sc.channel_url = 'https://www.sooplive.com/station/default02' AND NOT EXISTS (SELECT 1 FROM streamerChannel_info sci WHERE sci.channel_id = sc.id);`,

  // 3. Updates for all 18 streamers to ensure latest values
  `UPDATE streamerChannel_info SET display_name = '맹수린', profile_image_url = 'https://profile.img.sooplive.co.kr/LOGO/be/beastrin/beastrin.jpg', debut_date = '2026-08-23', debut_time = '14:00', start_at_utc = '2026-08-23T05:00:00.000Z', country_code = 'KR' WHERE channel_id IN (SELECT id FROM streamerChannel WHERE platform = 'SOOP' AND channel_url = 'https://www.sooplive.com/station/beastrin');`,
  `UPDATE streamerChannel_info SET display_name = '율개_', profile_image_url = 'https://profile.img.sooplive.co.kr/LOGO/cy/cy930221/cy930221.jpg', debut_date = '2026-08-24', debut_time = '20:00', start_at_utc = '2026-08-24T11:00:00.000Z', country_code = 'KR' WHERE channel_id IN (SELECT id FROM streamerChannel WHERE platform = 'SOOP' AND channel_url = 'https://www.sooplive.com/station/cy930221');`,
  `UPDATE streamerChannel_info SET display_name = '토모♪', profile_image_url = 'https://profile.img.sooplive.co.kr/LOGO/wa/warabimochi0/warabimochi0.jpg', debut_date = '2026-08-25', debut_time = '13:00', start_at_utc = '2026-08-25T04:00:00.000Z', country_code = 'KR' WHERE channel_id IN (SELECT id FROM streamerChannel WHERE platform = 'SOOP' AND channel_url = 'https://www.sooplive.com/station/warabimochi0');`,
  `UPDATE streamerChannel_info SET display_name = '癒月沙羅🍀ゆゆんが', profile_image_url = 'https://yt3.googleusercontent.com/1DvFwUHExxqmtroIWBDegjKg7BS9Mry_XDLbWqJitmCKSjy4ZTg2ibaYhvGOoieRf-n7LGEP2A=s900-c-k-c0x00ffffff-no-rj', debut_date = '2026-08-25', debut_time = '20:25', start_at_utc = '2026-08-25T11:25:00.000Z', country_code = 'JP' WHERE channel_id IN (SELECT id FROM streamerChannel WHERE platform = 'YOUTUBE' AND channel_url = 'https://www.youtube.com/@yuyunga');`,
  `UPDATE streamerChannel_info SET display_name = 'ねむくま まふゆ / Mafuyu Nemukuma', profile_image_url = 'https://yt3.googleusercontent.com/8rEJVyB0qOUdeBJIQ1cpwgHWr5MK79CZN_OpwWjLf-W7aa952QNE2TdN5Evx4ER7VaVPr9lo=s900-c-k-c0x00ffffff-no-rj', debut_date = '2026-08-25', debut_time = '21:00', start_at_utc = '2026-08-25T12:00:00.000Z', country_code = 'JP' WHERE channel_id IN (SELECT id FROM streamerChannel WHERE platform = 'YOUTUBE' AND channel_url = 'https://www.youtube.com/channel/UCT0D59ZmybXfae08GiMHSlQ');`,
  `UPDATE streamerChannel_info SET display_name = '請叫我披薩 Pinasalia', profile_image_url = 'https://yt3.googleusercontent.com/g1I-yjW-28oEfg171nul0cCm5_9p0XjGNbZXM5ymlIIUojs6_3IKFGdo5EaE8M5DWNRwR5-DPQ0=s900-c-k-c0x00ffffff-no-rj', debut_date = '2026-08-25', debut_time = '21:00', start_at_utc = '2026-08-25T12:00:00.000Z', country_code = 'US' WHERE channel_id IN (SELECT id FROM streamerChannel WHERE platform = 'YOUTUBE' AND channel_url = 'https://www.youtube.com/channel/UCx6rTx9V_chxAkn4luzyRpQ');`,
  `UPDATE streamerChannel_info SET display_name = '다번님', profile_image_url = 'https://nng-phinf.pstatic.net/MjAyNjA4MTZfMTM3/MDAxNzg2ODYyOTk2NTI2.qNOvNrmMICOLSE_CR8ONO0zpcyIAybvux8RmlK04WAAg.Bdt9zOZQkxqL_PlUdCefUyEWzMYZuKqEXDhEFFRtxz8g.PNG/image.png', debut_date = '2026-08-26', debut_time = '14:00', start_at_utc = '2026-08-26T05:00:00.000Z', country_code = 'KR' WHERE channel_id IN (SELECT id FROM streamerChannel WHERE platform = 'CHZZK' AND channel_url = 'https://chzzk.naver.com/3a5cc666e57aee0eb797a10d6e710fb2');`,
  `UPDATE streamerChannel_info SET display_name = '0ml 제로미리', profile_image_url = 'https://nng-phinf.pstatic.net/MjAyNjA2MTRfMTI4/MDAxNzgxNDM4NzY0NDEw.1oQwHG18HvYb2YJkhvg9RbBKiVXdAN36-Lk0r-6nVkwg.csLLADplFXzAYGH7oabedr7aXelpWiAdW6f8JAIi9eUg.JPEG/image.jpg', debut_date = '2026-08-28', debut_time = '12:00', start_at_utc = '2026-08-28T03:00:00.000Z', country_code = 'KR' WHERE channel_id IN (SELECT id FROM streamerChannel WHERE platform = 'CHZZK' AND channel_url = 'https://chzzk.naver.com/90d8df90bfb9b2a2a1aaf6a3f09d1221');`,
  `UPDATE streamerChannel_info SET display_name = '슷쟝、', profile_image_url = 'https://profile.img.sooplive.co.kr/LOGO/jj/jjrroesem/jjrroesem.jpg', debut_date = '2026-08-28', debut_time = '14:00', start_at_utc = '2026-08-28T05:00:00.000Z', country_code = 'KR' WHERE channel_id IN (SELECT id FROM streamerChannel WHERE platform = 'SOOP' AND channel_url = 'https://www.sooplive.com/station/jjrroesem');`,
  `UPDATE streamerChannel_info SET display_name = '시노미야 카나', profile_image_url = 'https://nng-phinf.pstatic.net/MjAyNTEyMjBfMTU3/MDAxNzY2MjIzMzA3OTQ1.fGLFXPbDy222nLnwo_zpxpFFvQEWng0gpnUouzzaEd8g.ZKXkkW2fpM3Dst0msddZR6c1um53GaT89WOb0mjORXIg.JPEG/image.jpg', debut_date = '2026-08-28', debut_time = '18:00', start_at_utc = '2026-08-28T09:00:00.000Z', country_code = 'KR' WHERE channel_id IN (SELECT id FROM streamerChannel WHERE platform = 'CHZZK' AND channel_url = 'https://chzzk.naver.com/dae941286535b489b5282a8910fb0363');`,
  `UPDATE streamerChannel_info SET display_name = '김레율 LEYUL', profile_image_url = 'https://nng-phinf.pstatic.net/MjAyNTAzMjNfMTM2/MDAxNzQyNzEwMDY4NzEx.S2Hn6yRoBeel1j-_-6MgTRUFgU3ZjT854l96H3PLybIg.ptbUifqkw2JYaZwwg2uMdEIv7BlCNSdBeq9F_DbJ0w4g.PNG/C15DF10A-457D-46EE-A6AE-94389F9D762E-1742710068.png', agency_name = 'STAR:VERSE', debut_date = '2026-08-28', debut_time = '20:00', start_at_utc = '2026-08-28T11:00:00.000Z', country_code = 'KR' WHERE channel_id IN (SELECT id FROM streamerChannel WHERE platform = 'CHZZK' AND channel_url = 'https://chzzk.naver.com/82e55f09f2235ac3d23c155bf20877de');`,
  `UPDATE streamerChannel_info SET display_name = '히모리 키코', profile_image_url = 'https://nng-phinf.pstatic.net/MjAyNjA4MThfNTYg/MDAxNzg2OTk1MjE0NzUw.hhUNRTUdiPXJZW-3TfubZh92HBzwhe3wezs9WxuekIkg.t_PN_pYqIMKNtqyMjdYNnTr93dgjyi3bawGYJ3cOc9cg.JPEG/image.jpg', debut_date = '2026-08-28', debut_time = '20:00', start_at_utc = '2026-08-28T11:00:00.000Z', country_code = 'KR' WHERE channel_id IN (SELECT id FROM streamerChannel WHERE platform = 'CHZZK' AND channel_url = 'https://chzzk.naver.com/dac7140d8871c1eb40dfc9dbdbdc4671');`,
  `UPDATE streamerChannel_info SET display_name = '홍림', profile_image_url = 'https://nng-phinf.pstatic.net/MjAyNjA4MTFfMjYy/MDAxNzg2NDU2MjAxNTgz.gl_y0Nd960O3Utle81yyo4BUwDBUDnv59NkyG1irausg.TFJ5cRWHS2c63COrvCSKugJEgl8VKipE2MpWz_J9alUg.PNG/image.png', debut_date = '2026-08-28', debut_time = '20:00', start_at_utc = '2026-08-28T11:00:00.000Z', country_code = 'KR' WHERE channel_id IN (SELECT id FROM streamerChannel WHERE platform = 'CHZZK' AND channel_url = 'https://chzzk.naver.com/8292f415bf4949a508539b1332e059dd');`,
  `UPDATE streamerChannel_info SET display_name = '쿄카_', profile_image_url = 'https://profile.img.sooplive.co.kr/LOGO/wa/waekqm/waekqm.jpg', debut_date = '2026-08-29', debut_time = '12:00', start_at_utc = '2026-08-29T03:00:00.000Z', country_code = 'KR' WHERE channel_id IN (SELECT id FROM streamerChannel WHERE platform = 'SOOP' AND channel_url = 'https://www.sooplive.com/station/waekqm');`,
  `UPDATE streamerChannel_info SET display_name = '햅하리 Hepharii', profile_image_url = 'https://nng-phinf.pstatic.net/MjAyNjA3MDVfMTIz/MDAxNzgzMjQxNjE3ODI2.suWJBK9Rd6-xlU3fAIg3BXye6W0Pus5plZBFeconTEAg.7VM8oZjeTzcpM7ks3c3C-XnDvNIA5wignN4M8k65OVIg.PNG/image.png', debut_date = '2026-08-29', debut_time = '12:00', start_at_utc = '2026-08-29T03:00:00.000Z', country_code = 'KR' WHERE channel_id IN (SELECT id FROM streamerChannel WHERE platform = 'CHZZK' AND channel_url = 'https://chzzk.naver.com/3b83140bc120a677646263b51d026fb8');`,
  `UPDATE streamerChannel_info SET display_name = '채루나 LUNA', profile_image_url = 'https://nng-phinf.pstatic.net/MjAyNjA4MjBfMjMz/MDAxNzg3MjIyNTA1ODcx.WZDTT-m7RC-Ro8wUY-qUz2bWQWgBI_kez_jgul31ahog.5iSh9stq6c9XeiNlfNKXafEOAKrzDSReBUlRREKUOgQg.PNG/image.png', agency_name = 'STAR:VERSE', debut_date = '2026-08-29', debut_time = '15:00', start_at_utc = '2026-08-29T06:00:00.000Z', country_code = 'KR' WHERE channel_id IN (SELECT id FROM streamerChannel WHERE platform = 'CHZZK' AND channel_url = 'https://chzzk.naver.com/8586c48ff92c6a2c7ba24937d4c360eb');`,
  `UPDATE streamerChannel_info SET display_name = 'yoru△03:10', profile_image_url = 'https://yt3.googleusercontent.com/SmC1yuSiHc7zRqlo0H2CMVWZj4NfoNhJd5fwdtKYZM9RXLITFKrdgLxaTinajfz5gWQ3npbZ=s900-c-k-c0x00ffffff-no-rj', debut_date = '2026-08-29', debut_time = '22:00', start_at_utc = '2026-08-29T13:00:00.000Z', country_code = 'JP' WHERE channel_id IN (SELECT id FROM streamerChannel WHERE platform = 'YOUTUBE' AND channel_url = 'https://www.youtube.com/@yoru0310');`,
  `UPDATE streamerChannel_info SET display_name = '연빛yeonvvit', profile_image_url = 'https://profile.img.sooplive.co.kr/LOGO/de/default02/default02.jpg', debut_date = '2026-08-30', debut_time = '14:00', start_at_utc = '2026-08-30T05:00:00.000Z', country_code = 'KR' WHERE channel_id IN (SELECT id FROM streamerChannel WHERE platform = 'SOOP' AND channel_url = 'https://www.sooplive.com/station/default02');`
];

console.log(`🚀 Executing ${queries.length} queries on remote D1 database (vdebut-db)...`);

for (let i = 0; i < queries.length; i++) {
  const q = queries[i];
  console.log(`\n[${i + 1}/${queries.length}] Executing: ${q.substring(0, 80)}...`);

  const res = spawnSync('cmd.exe', ['/c', 'npx', 'wrangler', 'd1', 'execute', 'vdebut-db', '--remote', `--command=${q}`, '--json'], {
    cwd: backendDir,
    encoding: 'utf-8'
  });

  if (res.status !== 0) {
    console.error(`❌ Query ${i + 1} failed with status ${res.status}`);
    console.error('stderr:', res.stderr);
    console.error('stdout:', res.stdout);
    process.exit(1);
  }

  try {
    const parsed = JSON.parse(res.stdout);
    console.log(`✅ Success: ${JSON.stringify(parsed[0]?.meta?.changes ?? 0)} changes, duration: ${parsed[0]?.meta?.duration ?? 0}ms`);
  } catch {
    console.log('✅ Success (non-json output received)');
  }
}

console.log('\n🎉 All Migration 0020 queries executed successfully on remote D1 database!');
